### ISSUE TITLE
Exploding SDK, causes system panic, crashes

### ISSUE THREAD

**Issue by notasecret** [peacemakr-io/peacemakr-go-sdk#34]
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x84364a]

goroutine 15 [running]:
github.com/peacemakr-io/peacemakr-go-sdk/pkg.(*standardPeacemakrSDK).getCryptoConfigCipher(0xc0000b8370, 0xb2)
	/go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/crypto_impl.go:1259 +0x2a
github.com/peacemakr-io/peacemakr-go-sdk/pkg.(*standardPeacemakrSDK).rotateClientKeyIfNeeded(0xc0000b8370, 0x0, 0x0)
	/go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/crypto_impl.go:1314 +0x9c
github.com/peacemakr-io/peacemakr-go-sdk/pkg.(*standardPeacemakrSDK).verifyRegistrationAndInit(0xc0000b8370, 0xc00010bd90, 0x4485eb)
	/go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/crypto_impl.go:1418 +0x50
github.com/peacemakr-io/peacemakr-go-sdk/pkg.(*standardPeacemakrSDK).Encrypt(0xc0000b8370, 0xc000360600, 0x5b8, 0x600, 0x5b8, 0x600, 0x5b8, 0x0, 0x0)
	/go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/crypto_impl.go:784 +0x2f
github.com/peacemakr-io/peacemakr-go-sdk/pkg.(*standardPeacemakrSDK).EncryptStr(0xc0000b8370, 0xc000360000, 0x5b8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/peacemakr-io/peacemakr-go-sdk/pkg/crypto_impl.go:267 +0x6e
main.runEncryptingClient(0x0, 0x7ffd7f8a1f53, 0x2c, 0x954264, 0x10, 0x64, 0xc000070360, 0xc0004cf6f0, 0x0, 0x0)
	/go/src/github.com/peacemakr-io/peacemakr-go-sdk/example/example.go:62 +0x728
created by main.main
	/go/src/github.com/peacemakr-io/peacemakr-go-sdk/example/example.go:186 +0x726
```

**Comment by notasecret** [comment]
Doesn't repro anymore.  Fix worked.
